export enum EventTypeEnum {
  FIXED_DATE = "DATAFIXA",
  CHECK_IN = 'CHECKIN',
  CHECK_OUT = 'CHECKOUT',
  BONIFICACAO = 'BONIFICACAO',
  EXPORTACAO = 'EXPORTACAO',
  PERMUTA = 'PERMUTA',
  SEM_CONTAS_RECEBER = 'SEMCONTASARECEBER',
  AUTORIZACAO_DE_FATURAMENTO_BANCARIO = 'AUTORIZACAOODEFATURAMENTOBANCARIO'
}
